sudo: required
addons:
  apt:
    packages:
    - git
    - make
    - curl
env:
  - DOCKER_IMAGE_NAME=cloudposse/bastion
services:
- docker
install:
- make init
- git diff -p -R --no-color | grep -E "^(diff|(old|new) mode)" --color=never | git apply
- ls -lR .
- make docker:login

script:
- make docker:build

after_success:
- make travis:docker-tag-and-push
