sudo: required
addons:
  apt:
    packages:
    - git
    - make
    - curl

env:
  - DOCKER_IMAGE_NAME=cloudposse/bastion

services:
- docker

install:
- make init
- make docker:login
# Travis has a default umask of 0002 before executing `git clone`.
# There is no workaround. Even git does not track directory modes.
# This has the unforunate consequance of granting g+rw to any directory we `ADD`.
- find rootfs/ -type d -exec chmod 755 {} \;

script:
- make docker:build

after_success:
- make travis:docker-tag-and-push
