#!/bin/bash

function _sigint() {
  echo -e '\nAborted'
  exit 1
}

trap _sigint SIGINT

for script in /etc/enforce.d/* ; do
  if [ -r $script ] && [ -x $script ]; then
    $script
    if [ $? -ne 0 ]; then
      echo "Access denied"
      exit 1
    fi
  fi
done



