#!/bin/bash 

if [ "${ENFORCER_ENABLED}" == "true" ]; then
  echo "- Enabling Enforcer"
  env | grep "^ENFORCER_" > /etc/enforcer
  grep -q "ForceCommand /usr/bin/enforcer" /etc/ssh/sshd_config || \
    echo "ForceCommand /usr/bin/enforcer" >> /etc/ssh/sshd_config
fi

if [ "${ENFORCER_ACLS_ENABLED}" == "true" ]; then
  echo "- Enabling Enforcer ACLs"
  chmod 755 /etc/enforce.d/?.acls
fi

if [ "${ENFORCER_SLACK_ENABLED}" == "true" ]; then
  echo "- Enabling Slack Notifications"
  env | grep "^SLACK_" > /etc/slack
  chmod 755 /etc/enforce.d/?.slack
fi
