#!/bin/bash

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

for script in /etc/ssh/sshrc.d/* ; do
  if [ -r $script ] ; then
    $script
    if [ $? -ne 0 ]; then
      echo "Goodbye"
      exit 1
    fi
  fi
done
