---
name: release
on:
  release:
    types:
      - published

permissions:
  id-token: write
  contents: write
  packages: write
  
jobs:
  terraform-module:
    uses: cloudposse/.github/.github/workflows/shared-release-branches.yml@main
    secrets: inherit

  ci-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"

      - name: Build GHR
        id: build-ghr
        uses: cloudposse/github-action-docker-build-push@main
        with:
          registry: ghcr.io
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
