name: release-published
on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write

jobs:
  controller-release-branches:
    uses: cloudposse/github-actions-workflows/.github/workflows/controller-release-branches.yml@main
