name: release-branch
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  id-token: write

jobs:
  ci-readme:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-readme.yml@main
    with:
      filter-mode: nofilter
      suggestions: false

  ci-codeowners:
    uses: cloudposse/github-actions-workflows/.github/workflows/ci-codeowners.yml@main
    with:
      is_fork: false
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}

  controller-release:
    uses: cloudposse/github-actions-workflows/.github/workflows/controller-release.yml@main
    needs: [ ci-readme, ci-codeowners ]
    secrets:
      github_access_token: ${{ secrets.REPO_ACCESS_TOKEN }}  # Required to trigger tag workflow
